Hello!

You have reached the Son of the LSM Robot, otherwise known as Sonny.
See below for what Sonny found out about your LSM entries.

If Sonny makes trouble, please contact his maintainer, Aaron Schrab,
at lsm-help@execpc.com.  Sonny is supposed to be a good boy.

BTW, please also upload the LSM entries to the ftp sites together with
your packages.  It makes it easier to browse the ftp sites.

<Over to you, Sonny.>

